[2024-01-31 15:28:53,580] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.get_data_covid manual__2024-01-31T15:28:52.259818+00:00 [queued]>
[2024-01-31 15:28:53,587] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.get_data_covid manual__2024-01-31T15:28:52.259818+00:00 [queued]>
[2024-01-31 15:28:53,588] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 15:28:53,588] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-01-31 15:28:53,588] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 15:28:53,597] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data_covid> on 2024-01-31 15:28:52.259818+00:00
[2024-01-31 15:28:53,601] {standard_task_runner.py:52} INFO - Started process 9987 to run task
[2024-01-31 15:28:53,604] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'get_data_covid', 'manual__2024-01-31T15:28:52.259818+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpns86s4xp', '--error-file', '/tmp/tmp3jm0d884']
[2024-01-31 15:28:53,605] {standard_task_runner.py:80} INFO - Job 189: Subtask get_data_covid
[2024-01-31 15:28:53,648] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.get_data_covid manual__2024-01-31T15:28:52.259818+00:00 [running]> on host d99f9e65d396
[2024-01-31 15:28:53,699] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=get_data_covid
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T15:28:52.259818+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-31T15:28:52.259818+00:00
[2024-01-31 15:28:56,743] {logging_mixin.py:115} INFO - Successfully install requests
[2024-01-31 15:28:56,809] {python.py:173} INFO - Done. Returned value was: get_data_covid
[2024-01-31 15:28:56,826] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=get_data_covid, execution_date=20240131T152852, start_date=20240131T152853, end_date=20240131T152856
[2024-01-31 15:28:56,851] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-31 15:28:56,882] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
