[2024-01-31 15:01:54,320] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-01-31T15:01:28.912806+00:00 [queued]>
[2024-01-31 15:01:54,326] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-01-31T15:01:28.912806+00:00 [queued]>
[2024-01-31 15:01:54,326] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 15:01:54,326] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-01-31 15:01:54,326] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 15:01:54,334] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): aggregate_dim_table> on 2024-01-31 15:01:28.912806+00:00
[2024-01-31 15:01:54,337] {standard_task_runner.py:52} INFO - Started process 8944 to run task
[2024-01-31 15:01:54,340] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'aggregate_dim_table', 'manual__2024-01-31T15:01:28.912806+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpjx7bw3af', '--error-file', '/tmp/tmpfmxk7jiz']
[2024-01-31 15:01:54,341] {standard_task_runner.py:80} INFO - Job 172: Subtask aggregate_dim_table
[2024-01-31 15:01:54,378] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-01-31T15:01:28.912806+00:00 [running]> on host d99f9e65d396
[2024-01-31 15:01:54,424] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=aggregate_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T15:01:28.912806+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-31T15:01:28.912806+00:00
[2024-01-31 15:01:57,253] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-01-31 15:02:00,073] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-01-31 15:02:03,019] {logging_mixin.py:115} INFO - Successfully install pymysql
[2024-01-31 15:02:05,905] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-01-31 15:02:05,961] {python.py:173} INFO - Done. Returned value was: insert dim table
[2024-01-31 15:02:05,978] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=aggregate_dim_table, execution_date=20240131T150128, start_date=20240131T150154, end_date=20240131T150205
[2024-01-31 15:02:06,005] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-31 15:02:06,024] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
