[2024-02-01 13:26:47,903] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-01T13:26:47.310511+00:00 [queued]>
[2024-02-01 13:26:47,911] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-01T13:26:47.310511+00:00 [queued]>
[2024-02-01 13:26:47,912] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 13:26:47,912] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-01 13:26:47,912] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 13:26:47,923] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): aggregate_dim_table> on 2024-02-01 13:26:47.310511+00:00
[2024-02-01 13:26:47,928] {standard_task_runner.py:52} INFO - Started process 3189 to run task
[2024-02-01 13:26:47,931] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'aggregate_dim_table', 'manual__2024-02-01T13:26:47.310511+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp678nqjj7', '--error-file', '/tmp/tmpu5mw4gmm']
[2024-02-01 13:26:47,932] {standard_task_runner.py:80} INFO - Job 252: Subtask aggregate_dim_table
[2024-02-01 13:26:47,979] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-01T13:26:47.310511+00:00 [running]> on host 0cb2a3b23a40
[2024-02-01 13:26:48,043] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=aggregate_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T13:26:47.310511+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-01T13:26:47.310511+00:00
[2024-02-01 13:26:51,162] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-01 13:26:54,107] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-01 13:26:56,989] {logging_mixin.py:115} INFO - Successfully install pymysql
[2024-02-01 13:26:59,924] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-01 13:26:59,996] {python.py:173} INFO - Done. Returned value was: insert dim table
[2024-02-01 13:27:00,015] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=aggregate_dim_table, execution_date=20240201T132647, start_date=20240201T132647, end_date=20240201T132700
[2024-02-01 13:27:00,067] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 13:27:00,085] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
