[2024-01-31 15:30:21,406] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.get_data_covid manual__2024-01-31T15:30:19.767407+00:00 [queued]>
[2024-01-31 15:30:21,414] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.get_data_covid manual__2024-01-31T15:30:19.767407+00:00 [queued]>
[2024-01-31 15:30:21,415] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 15:30:21,415] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-01-31 15:30:21,415] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 15:30:21,427] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data_covid> on 2024-01-31 15:30:19.767407+00:00
[2024-01-31 15:30:21,431] {standard_task_runner.py:52} INFO - Started process 10096 to run task
[2024-01-31 15:30:21,435] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'get_data_covid', 'manual__2024-01-31T15:30:19.767407+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpdvqz68eb', '--error-file', '/tmp/tmpj3d7ca3k']
[2024-01-31 15:30:21,436] {standard_task_runner.py:80} INFO - Job 193: Subtask get_data_covid
[2024-01-31 15:30:21,480] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.get_data_covid manual__2024-01-31T15:30:19.767407+00:00 [running]> on host d99f9e65d396
[2024-01-31 15:30:21,532] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=get_data_covid
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T15:30:19.767407+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-31T15:30:19.767407+00:00
[2024-01-31 15:30:24,471] {logging_mixin.py:115} INFO - Successfully install requests
[2024-01-31 15:30:24,539] {python.py:173} INFO - Done. Returned value was: get_data_covid
[2024-01-31 15:30:24,554] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=get_data_covid, execution_date=20240131T153019, start_date=20240131T153021, end_date=20240131T153024
[2024-01-31 15:30:24,569] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-31 15:30:24,597] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
