[2024-01-31 13:27:39,861] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.create_ddl_postgres manual__2024-01-31T13:27:27.422828+00:00 [queued]>
[2024-01-31 13:27:39,869] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.create_ddl_postgres manual__2024-01-31T13:27:27.422828+00:00 [queued]>
[2024-01-31 13:27:39,870] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 13:27:39,870] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-01-31 13:27:39,870] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 13:27:39,881] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_ddl_postgres> on 2024-01-31 13:27:27.422828+00:00
[2024-01-31 13:27:39,886] {standard_task_runner.py:52} INFO - Started process 6110 to run task
[2024-01-31 13:27:39,889] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'create_ddl_postgres', 'manual__2024-01-31T13:27:27.422828+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpqb3nm0oi', '--error-file', '/tmp/tmpwyt_vsjx']
[2024-01-31 13:27:39,890] {standard_task_runner.py:80} INFO - Job 113: Subtask create_ddl_postgres
[2024-01-31 13:27:39,936] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.create_ddl_postgres manual__2024-01-31T13:27:27.422828+00:00 [running]> on host d99f9e65d396
[2024-01-31 13:27:39,994] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=create_ddl_postgres
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T13:27:27.422828+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-31T13:27:27.422828+00:00
[2024-01-31 13:27:42,857] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-01-31 13:27:42,898] {logging_mixin.py:115} INFO - success migrate table
[2024-01-31 13:27:42,899] {python.py:173} INFO - Done. Returned value was: None
[2024-01-31 13:27:42,909] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=create_ddl_postgres, execution_date=20240131T132727, start_date=20240131T132739, end_date=20240131T132742
[2024-01-31 13:27:42,928] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-31 13:27:42,964] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
