[2024-02-02 04:13:39,921] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-02T04:13:21.812451+00:00 [queued]>
[2024-02-02 04:13:39,926] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-02T04:13:21.812451+00:00 [queued]>
[2024-02-02 04:13:39,926] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-02 04:13:39,926] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-02 04:13:39,926] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-02 04:13:39,933] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): aggregate_dim_table> on 2024-02-02 04:13:21.812451+00:00
[2024-02-02 04:13:39,936] {standard_task_runner.py:52} INFO - Started process 909 to run task
[2024-02-02 04:13:39,939] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'aggregate_dim_table', 'manual__2024-02-02T04:13:21.812451+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpdckklsrl', '--error-file', '/tmp/tmpzjpxk3w0']
[2024-02-02 04:13:39,940] {standard_task_runner.py:80} INFO - Job 313: Subtask aggregate_dim_table
[2024-02-02 04:13:39,969] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-02T04:13:21.812451+00:00 [running]> on host c3bb523480bf
[2024-02-02 04:13:40,007] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=aggregate_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2024-02-02T04:13:21.812451+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-02T04:13:21.812451+00:00
[2024-02-02 04:13:42,245] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-02 04:13:44,481] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-02 04:13:46,717] {logging_mixin.py:115} INFO - Successfully install pymysql
[2024-02-02 04:13:48,947] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-02 04:13:49,003] {python.py:173} INFO - Done. Returned value was: insert dim table
[2024-02-02 04:13:49,017] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=aggregate_dim_table, execution_date=20240202T041321, start_date=20240202T041339, end_date=20240202T041349
[2024-02-02 04:13:49,030] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-02 04:13:49,051] {local_task_job.py:273} INFO - 5 downstream tasks scheduled from follow-on schedule check
