[2024-02-01 13:48:24,183] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.create_ddl_postgres manual__2024-02-01T13:48:23.614829+00:00 [queued]>
[2024-02-01 13:48:24,190] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.create_ddl_postgres manual__2024-02-01T13:48:23.614829+00:00 [queued]>
[2024-02-01 13:48:24,191] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 13:48:24,191] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-01 13:48:24,191] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 13:48:24,202] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_ddl_postgres> on 2024-02-01 13:48:23.614829+00:00
[2024-02-01 13:48:24,207] {standard_task_runner.py:52} INFO - Started process 4020 to run task
[2024-02-01 13:48:24,226] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'create_ddl_postgres', 'manual__2024-02-01T13:48:23.614829+00:00', '--job-id', '268', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp9nm9_41y', '--error-file', '/tmp/tmp3nq6a400']
[2024-02-01 13:48:24,230] {standard_task_runner.py:80} INFO - Job 268: Subtask create_ddl_postgres
[2024-02-01 13:48:24,300] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.create_ddl_postgres manual__2024-02-01T13:48:23.614829+00:00 [running]> on host 0cb2a3b23a40
[2024-02-01 13:48:24,395] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=create_ddl_postgres
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T13:48:23.614829+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-01T13:48:23.614829+00:00
[2024-02-01 13:48:27,911] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-01 13:48:31,407] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-01 13:48:31,454] {logging_mixin.py:115} INFO - success migrate table
[2024-02-01 13:48:31,454] {python.py:173} INFO - Done. Returned value was: None
[2024-02-01 13:48:31,469] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=create_ddl_postgres, execution_date=20240201T134823, start_date=20240201T134824, end_date=20240201T134831
[2024-02-01 13:48:31,504] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 13:48:31,527] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
