[2024-01-31 15:07:18,563] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.get_data_covid manual__2024-01-31T15:07:16.557152+00:00 [queued]>
[2024-01-31 15:07:18,570] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.get_data_covid manual__2024-01-31T15:07:16.557152+00:00 [queued]>
[2024-01-31 15:07:18,570] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 15:07:18,570] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-01-31 15:07:18,570] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 15:07:18,580] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data_covid> on 2024-01-31 15:07:16.557152+00:00
[2024-01-31 15:07:18,584] {standard_task_runner.py:52} INFO - Started process 9116 to run task
[2024-01-31 15:07:18,586] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'get_data_covid', 'manual__2024-01-31T15:07:16.557152+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpcs2fs2w6', '--error-file', '/tmp/tmpcky6k_4h']
[2024-01-31 15:07:18,588] {standard_task_runner.py:80} INFO - Job 173: Subtask get_data_covid
[2024-01-31 15:07:18,631] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.get_data_covid manual__2024-01-31T15:07:16.557152+00:00 [running]> on host d99f9e65d396
[2024-01-31 15:07:18,687] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=get_data_covid
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T15:07:16.557152+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-31T15:07:16.557152+00:00
[2024-01-31 15:07:21,634] {logging_mixin.py:115} INFO - Successfully install requests
[2024-01-31 15:07:21,716] {python.py:173} INFO - Done. Returned value was: get_data_covid
[2024-01-31 15:07:21,732] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=get_data_covid, execution_date=20240131T150716, start_date=20240131T150718, end_date=20240131T150721
[2024-01-31 15:07:21,784] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-31 15:07:21,814] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
